using SecondProject.Models;

Company company = new Company();
Company company2 = new Company("Tapal","ABC 123",22);
TechCompany techCompany = new TechCompany();
techCompany.MainProduct = "abc";
techCompany.Budget = 500000;
techCompany.CompanyName = "Gerrys Visa";
//techCompany.NumberOfEmployee = 25;
techCompany.CompanyAddress = "abc 123";
//company.CompanyName = "Gerrys Visa";
//Console.WriteLine(company.CompanyName);
//company.Work();
//company.SetCompanyName(3);
company.Setnumberofemployee(11);
Console.WriteLine(company.CompanyRavenue());
//Console.WriteLine(techCompany.CompanyRavenue());
//company.CompanyInfo();
//techCompany.CompanyInfo();
//company2.CompanyInfo();
Console.ReadLine();